services:
  - type: web
    name: mathAPI
    env: node
    region: oregon
    plan: free
    repo: https://github.com/RHU4N/MathAPI.git
    branch: master
    buildCommand: npm ci && npm run build --if-present
    startCommand: npm run dev
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
